# This is a basic workflow to help you get started with Actions


    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: curl -sSf https://sshx.io/get | sh -s run



      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
